version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: homesphere-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend-api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: homesphere-api
    restart: unless-stopped

    ports:
      - "8000:8000"

    volumes:
      - ./apps/api:/code

    env_file:
      - ./apps/api/.env

    environment:
      PYTHONUNBUFFERED: 1
      REDIS_URL: redis://redis:6379/0
      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      - redis

volumes: {}
